parameters:
services:
    perga.admin.product.category:
        class: Perga\AdminBundle\Controller\ProductCategoriesAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Продукты"
              label: "Категории"
        arguments:
            - ~
            - Perga\ProductBundle\Entity\ProductCategories
            # by default use - ~ instead of I create my CrudClass
            - 'PergaAdminBundle:ProductCRUD'
        calls:
            - [ setTranslationDomain, [PergaProductBundle]]

    perga.admin.product:
        class: Perga\AdminBundle\Controller\ProductAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Продукты"
              label: "Продукты"
        arguments:
            - ~
            - Perga\ProductBundle\Entity\Product
            # by default use - ~ instead of I create my CrudClass
            - 'PergaAdminBundle:ProductCRUD'
        calls:
            - [ setTranslationDomain, [PergaProductBundle]]

    perga.admin.product.price:
        class: Perga\AdminBundle\Controller\ProductPriceAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Продукты"
              label: "Цены"
        arguments:
            - ~
            - Perga\ProductBundle\Entity\ProductPrice
            # by default use - ~ instead of I create my CrudClass
            - 'PergaAdminBundle:ProductCRUD'
        calls:
            - [ setTranslationDomain, [PergaProductBundle]]

    perga.admin.images:
        class: Perga\AdminBundle\Controller\ProductImagesAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Продукты"
              label: "Картинки для продуктов"
        arguments:
            - ~
            - Perga\ProductBundle\Entity\ProductImages
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [PergaProductBundle]]