parameters:
services:
    perga.admin.product:
        class: Perga\AdminBundle\Controller\ProductAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Продукты"
              label: "Продукты"
        arguments:
            - ~
            - Perga\ProductBundle\Entity\Products
            # by default use - ~ instead of I create my CrudClass
            - 'PergaAdminBundle:ProductCRUD'
        calls:
            - [ setTranslationDomain, [PergaProductBundle]]
    perga.admin.images:
        class: Perga\AdminBundle\Controller\ProductImagesAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Продукты"
              label: "Картинки для продуктов"
        arguments:
            - ~
            - Perga\ProductBundle\Entity\ProductImages
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [PergaProductBundle]]