parameters:
    product.model.class:   Perga\ProductBundle\Services\ProductModel
services:
    perga.model.product:
        class: "%product.model.class%"
        arguments:    [@doctrine.orm.entity_manager]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }